# Generated by Django 4.2.7 on 2023-12-04 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissionMindApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='date',
            field=models.DateField(default=datetime.date(2023, 12, 1)),
        ),
    ]
