# Generated by Django 4.2.7 on 2023-12-08 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MissionMindApp', '0002_survey_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='question2',
            new_name='anxiety',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='question3',
            new_name='homesickness',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='question4',
            new_name='satisfaction',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='question5',
            new_name='sleep',
        ),
        migrations.RenameField(
            model_name='survey',
            old_name='question1',
            new_name='stress',
        ),
        migrations.AddField(
            model_name='survey',
            name='spirit',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='survey',
            name='name',
            field=models.CharField(max_length=240, verbose_name='name'),
        ),
    ]
